/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcvicovaniPisnicekRouteImport } from './routes/procvicovani-pisnicek'
import { Route as ProcvicovaniAkorduRouteImport } from './routes/procvicovani-akordu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AkordyRouteImport } from './routes/akordy'
import { Route as IndexRouteImport } from './routes/index'

const ProcvicovaniPisnicekRoute = ProcvicovaniPisnicekRouteImport.update({
  id: '/procvicovani-pisnicek',
  path: '/procvicovani-pisnicek',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcvicovaniAkorduRoute = ProcvicovaniAkorduRouteImport.update({
  id: '/procvicovani-akordu',
  path: '/procvicovani-akordu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AkordyRoute = AkordyRouteImport.update({
  id: '/akordy',
  path: '/akordy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akordy': typeof AkordyRoute
  '/login': typeof LoginRoute
  '/procvicovani-akordu': typeof ProcvicovaniAkorduRoute
  '/procvicovani-pisnicek': typeof ProcvicovaniPisnicekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akordy': typeof AkordyRoute
  '/login': typeof LoginRoute
  '/procvicovani-akordu': typeof ProcvicovaniAkorduRoute
  '/procvicovani-pisnicek': typeof ProcvicovaniPisnicekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akordy': typeof AkordyRoute
  '/login': typeof LoginRoute
  '/procvicovani-akordu': typeof ProcvicovaniAkorduRoute
  '/procvicovani-pisnicek': typeof ProcvicovaniPisnicekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akordy'
    | '/login'
    | '/procvicovani-akordu'
    | '/procvicovani-pisnicek'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akordy'
    | '/login'
    | '/procvicovani-akordu'
    | '/procvicovani-pisnicek'
  id:
    | '__root__'
    | '/'
    | '/akordy'
    | '/login'
    | '/procvicovani-akordu'
    | '/procvicovani-pisnicek'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkordyRoute: typeof AkordyRoute
  LoginRoute: typeof LoginRoute
  ProcvicovaniAkorduRoute: typeof ProcvicovaniAkorduRoute
  ProcvicovaniPisnicekRoute: typeof ProcvicovaniPisnicekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procvicovani-pisnicek': {
      id: '/procvicovani-pisnicek'
      path: '/procvicovani-pisnicek'
      fullPath: '/procvicovani-pisnicek'
      preLoaderRoute: typeof ProcvicovaniPisnicekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procvicovani-akordu': {
      id: '/procvicovani-akordu'
      path: '/procvicovani-akordu'
      fullPath: '/procvicovani-akordu'
      preLoaderRoute: typeof ProcvicovaniAkorduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akordy': {
      id: '/akordy'
      path: '/akordy'
      fullPath: '/akordy'
      preLoaderRoute: typeof AkordyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkordyRoute: AkordyRoute,
  LoginRoute: LoginRoute,
  ProcvicovaniAkorduRoute: ProcvicovaniAkorduRoute,
  ProcvicovaniPisnicekRoute: ProcvicovaniPisnicekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
